Add ci permissions to plan and dry-run
UKHomeOffice/acp-infra pull request #15
Opened 2017-08-10 11:14 UTC by lewismarshall

2017-08-14 08:57 UTC, KashifSaadat requested changes
One minor typo, otherwise LGTM.

2017-08-14 08:57 UTC, KashifSaadat commented on variables.tf
> +variable "terrafrom_lock_table" {
Minor typo in variable name, `terrafrom_lock_table` to `terraform_lock_table`.

2017-08-14 08:57 UTC, KashifSaadat commented on users.tf
> +            "Resource": "arn:aws:dynamodb:::table/${var.terrafrom_lock_table}"
Update variable name reference once corrected.

2017-08-15 11:05 UTC, gambol99 commented on variables.tf
> +  description = "The terraform bucket name used for state"
default = ""

2017-08-15 11:15 UTC, lewismarshall commented on variables.tf
> +  description = "The terraform bucket name used for state"
@gambol99 all done

2017-08-15 13:24 UTC, KashifSaadat approved these changes
LGTM

2017-08-15 14:38 UTC, gambol99 approved these changes

2017-08-15 14:41 UTC, merged